name: 'tcc'
description: 'roda todos os testes a cada push no repositorio'
author: 'Leandro Abreu'

inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
  TENOR_TOKEN:
    description: 'Tenor API token'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'